output_folder_path: 'results/outputs/rnn_512n_4l_weight20'
length: 30
resolution: 0.2
instrument_name: 'Acoustic Grand Piano'
model:
  hidden_size: 256
  num_layers:  4
model_weights_path: 'results/models/rnn_512n_4l_weight20_pretrained100.pt'
device: 'cuda:0'
sample_file_path: 'data/maestro-v3.0.0/2004/MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_05_Track05_wav.midi'
sample_timestamps_cnt: 30