experiment_name: 'rnn_512n_4l_weight20'
pretrained_weights_path: null
num_epochs: 50
device: 'cuda:0'
resolution: 0.2
train_tokens_path: 'data/train_tokens.csv'
val_tokens_path: 'data/val_tokens.csv'
model:
  hidden_size: 512
  num_layers:  4
optimizer:
  learning_rate: 0.0004
  weight_decay: 0.0001
scheduler:
  period: 10
  factor: 1
loss:
  pos_weight: 20