experiment_name: 'rnn_512n_4l_adam3e-4_cos10'
num_epochs: 50
device: 'cuda:0'
train_size: 0.9
resolution: 0.2
dataset_path: 'data/maestro-v3.0.0'
model:
  hidden_size: 512
  num_layers:  4
optimizer:
  learning_rate: 0.0004
  weight_decay: 0.0001
scheduler:
  period: 10
  factor: 1
loss:
  pos_weight: 32